Select location editor text on focus
SerenityOS/ladybird pull request #112
Opened 2022-11-07 22:21 UTC by checksum-fail

This PR lets us match the behavior of other browsers when clicking to
focus the location editor.

2022-11-13 20:28 UTC, ADKaster commented on LocationEdit.cpp
> +    QTimer::singleShot(0, this, &QLineEdit::selectAll);
hm. This functionality looks pretty simple. Are we sure there's not a builtin way to achieve this with the base QLineEdit class? possibly with signals and slots on that class or its parent?

2022-11-13 20:36 UTC, checksum-fail commented on LocationEdit.cpp
> +    QTimer::singleShot(0, this, &QLineEdit::selectAll);
AFAICT there is no `focusChanged` (or equivalent) signal for QLineEdit. I'm not familiar enough with Qt to provide a more knowledgeable answer.

2022-11-14 09:52 UTC, elcuco commented on LocationEdit.cpp
> +    QTimer::singleShot(0, this, &QLineEdit::selectAll);
You can create an event filter in the main window - which will emit a signal - and install it into the line edit. You do not need to subclass.

https://forum.qt.io/topic/110350/how-to-make-an-eventfilter

2022-11-14 14:21 UTC, elcuco commented on LocationEdit.h
> +#define AK_DONT_REPLACE_STD
You are not including AK here, you don't need this define.

2022-11-14 20:52 UTC, checksum-fail commented on LocationEdit.cpp
> +    QTimer::singleShot(0, this, &QLineEdit::selectAll);
> You can create an event filter in the main window

I tried following this according to the instructions in the link that you provided, and I ended up with a steady stream of errors which led me to documentation referencing `"ui_mainwindow.h"` and  a `.ui` file for User Interface Compiler, which I could not find in Ladybird.

I arrived at the current solution, which works as intended and eliminates the subclass. If there is a way to clean this up a bit more, please let me know.

2022-11-15 12:37 UTC, elcuco commented on LocationEdit.cpp
> +    QTimer::singleShot(0, this, &QLineEdit::selectAll);
MUCH CLEANER! NICELY DONE!

Another improvement you can make - is to compare the pointer of the object, against `m_current_tab->m_location_edit` instead (this is simpler then comparing strings). Your code will also break if we focus another kind of line edit (theoretically, in the future - I am not sure we have another one right now).

BTW, why are you running a single shot timer, instead of directly calling a function? (is this call on another thread?). This trick is used when you are doing a heavy job and want to delegate heavy job into another time slot.

2022-11-15 12:39 UTC, elcuco commented on BrowserWindow.cpp
> +    if(!strcmp(object->metaObject()->className(), "QLineEdit") && event->type() == QEvent::FocusIn) {
```suggestion
    // note the wrong spacing in your original code, run `clang-format -i BrwoserWindow.cpp` 
    if (m_current_tab->m_location_edit == object  && event->type() == QEvent::FocusIn) {
```

2022-11-15 12:42 UTC, elcuco commented on BrowserWindow.cpp
> +    QCoreApplication::instance()->installEventFilter(this);
you can also install the event filter on the main window, not the core app. It will get less hits. Maybe even the line edit itself - please try it.

2022-11-15 15:33 UTC, checksum-fail commented on LocationEdit.cpp
> +    QTimer::singleShot(0, this, &QLineEdit::selectAll);
> MUCH CLEANER! NICELY DONE!

Thank you, I appreciate your help. :^)

> Another improvement you can make - is to compare the pointer of the object, against `m_current_tab->m_location_edit` instead (this is simpler then comparing strings). Your code will also break if we focus another kind of line edit (theoretically, in the future - I am not sure we have another one right now).

I do compare `object == m_current_tab->m_location_edit` in the `eventFilter` function. It looks like I can replace the `className` comparison with a check that `m_current_tab` is not null, so I will do that.

> BTW, why are you running a single shot timer, instead of directly calling a function? (is this call on another thread?). This trick is used when you are doing a heavy job and want to delegate heavy job into another time slot.

I tried calling `selectAll()` directly, this does not seem to work due to how events propagate. After a bit of research, it appears the most common way to implement this functionality is to use the single shot timer method.

2022-11-15 15:58 UTC, checksum-fail commented on BrowserWindow.cpp
> +    QCoreApplication::instance()->installEventFilter(this);
I tried to install the `eventFilter` on the `BrowserWindow` object and the `QLineEdit`, unfortunately I could not find a workable solution.

2022-11-17 06:12 UTC, elcuco requested changes
I see the problem: when we create a new tab, we forcely load a "about:blank" page, to initialize the JS debugger view, which messes up you idea.  This PR is just not working.

I have an implementation which works as you intend - I did hook into `QTabWidget::currentChanged` which means modification inside the browser window only (..and exposing some internals from `Tab` as by now they are internal/private members).

2022-11-17 13:53 UTC, checksum-fail commented
> I see the problem: when we create a new tab, we forcely load a "about:blank" page, to initialize the JS debugger view, which messes up you idea. This PR is just not working.
> 
> I have an implementation which works as you intend - I did hook into `QTabWidget::currentChanged` which means modification inside the browser window only (..and exposing some internals from `Tab` as by now they are internal/private members).

Ok, closing this PR and will wait for a more sensible solution to be implemented.

2022-11-17 13:53 UTC, closed without merging